server:
  port: 0

spring:
  profiles:
    active: local

  redis:
    host: ${UNIQUONE_REDIS}
    port: 6379

  data:
    mongodb:
      uri: ${UNIQUONE_MONGODB}

  application:
    name: uniquone-chat-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG

token:
  expiration_time: 864000000
  secret: user_token_uniqu_native_ecommerce
  name: Authorization

refreshToken:
  expiration_time: 2592000000
  name: refreshToken