server:
  port: 0

spring:
  profiles:
    active: local

  redis:
    host: 127.0.0.1
    port: 6379

  data:
    mongodb:
      uri: ${UNIQUONE_MONGODB}

  application:
    name: uniquone-chat-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA-SERVER}
      
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG

