server:
  port: 7080

spring:
  redis:
    host: ${UNIQUONE_REDIS}
    port: ${UNIQUONE_REDIS_PORT}
  data:
    mongodb:
      uri: ${UNIQUONE_MONGODB}
  application:
    name: uniquone-chat-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG